spring:
  application:
    name: LivrariaApplication
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/livrariadb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update

  logging:
    level:
      org.springframework: DEBUG
      com.seuprojeto: DEBUG
      org.hibernate: DEBUG
      root: ERROR